import type { Product, Category, Account, Customer } from "@/lib/types"

export const categories: Omit<Category, "_id">[] = [
  {
    name: "Housekeeping Materials",
    slug: "housekeeping",
    description: "Cleaning supplies and housekeeping essentials",
    isActive: true,
  },
  { name: "Safety Items", slug: "safety", description: "Safety equipment and protective gear", isActive: true },
  {
    name: "Account Books",
    slug: "account-books",
    description: "Ledgers, registers and accounting books",
    isActive: true,
  },
  { name: "Industrial Supplies", slug: "industrial", description: "Industrial tools and supplies", isActive: true },
  { name: "Office Stationery", slug: "office", description: "Pens, papers, and office supplies", isActive: true },
]

export const products: Omit<Product, "_id" | "createdAt" | "updatedAt">[] = [
  // Housekeeping Materials
  {
    name: "Floor Cleaner - 5L",
    description: "Premium floor cleaning solution",
    category: "housekeeping",
    price: 450,
    costPrice: 320,
    quantity: 50,
    minStock: 10,
    unit: "bottle",
    sku: "HK001",
    images: [],
    isActive: true,
  },
  {
    name: "Mop Set with Bucket",
    description: "Heavy duty mop with wringer bucket",
    category: "housekeeping",
    price: 890,
    costPrice: 650,
    quantity: 25,
    minStock: 5,
    unit: "set",
    sku: "HK002",
    images: [],
    isActive: true,
  },
  {
    name: "Dusting Cloths (Pack of 12)",
    description: "Microfiber dusting cloths",
    category: "housekeeping",
    price: 299,
    costPrice: 180,
    quantity: 100,
    minStock: 20,
    unit: "pack",
    sku: "HK003",
    images: [],
    isActive: true,
  },
  {
    name: "Glass Cleaner Spray - 500ml",
    description: "Streak-free glass cleaner",
    category: "housekeeping",
    price: 185,
    costPrice: 120,
    quantity: 75,
    minStock: 15,
    unit: "bottle",
    sku: "HK004",
    images: [],
    isActive: true,
  },

  // Safety Items
  {
    name: "Safety Helmet - Yellow",
    description: "Industrial safety helmet with adjustable strap",
    category: "safety",
    price: 350,
    costPrice: 220,
    quantity: 40,
    minStock: 10,
    unit: "piece",
    sku: "SF001",
    images: [],
    isActive: true,
  },
  {
    name: "Safety Gloves (Pair)",
    description: "Cut-resistant work gloves",
    category: "safety",
    price: 180,
    costPrice: 110,
    quantity: 100,
    minStock: 20,
    unit: "pair",
    sku: "SF002",
    images: [],
    isActive: true,
  },
  {
    name: "Safety Goggles",
    description: "Anti-fog protective eyewear",
    category: "safety",
    price: 250,
    costPrice: 150,
    quantity: 60,
    minStock: 15,
    unit: "piece",
    sku: "SF003",
    images: [],
    isActive: true,
  },
  {
    name: "First Aid Kit - 50 Items",
    description: "Complete first aid emergency kit",
    category: "safety",
    price: 1200,
    costPrice: 800,
    quantity: 20,
    minStock: 5,
    unit: "kit",
    sku: "SF004",
    images: [],
    isActive: true,
  },

  // Account Books
  {
    name: "Cash Book - 500 Pages",
    description: "Hardbound cash book with numbered pages",
    category: "account-books",
    price: 380,
    costPrice: 240,
    quantity: 30,
    minStock: 10,
    unit: "book",
    sku: "AB001",
    images: [],
    isActive: true,
  },
  {
    name: "Ledger Book - 400 Pages",
    description: "Premium ledger with index pages",
    category: "account-books",
    price: 420,
    costPrice: 280,
    quantity: 25,
    minStock: 8,
    unit: "book",
    sku: "AB002",
    images: [],
    isActive: true,
  },
  {
    name: "Journal Register",
    description: "Bound journal for daily entries",
    category: "account-books",
    price: 290,
    costPrice: 180,
    quantity: 40,
    minStock: 10,
    unit: "book",
    sku: "AB003",
    images: [],
    isActive: true,
  },
  {
    name: "Stock Register",
    description: "Inventory tracking register",
    category: "account-books",
    price: 320,
    costPrice: 200,
    quantity: 35,
    minStock: 10,
    unit: "book",
    sku: "AB004",
    images: [],
    isActive: true,
  },

  // Industrial Supplies
  {
    name: "Industrial Tape - 48mm x 50m",
    description: "Heavy duty packaging tape",
    category: "industrial",
    price: 120,
    costPrice: 75,
    quantity: 200,
    minStock: 50,
    unit: "roll",
    sku: "IN001",
    images: [],
    isActive: true,
  },
  {
    name: "Cable Ties - Pack of 100",
    description: "Nylon cable ties 200mm",
    category: "industrial",
    price: 150,
    costPrice: 90,
    quantity: 150,
    minStock: 30,
    unit: "pack",
    sku: "IN002",
    images: [],
    isActive: true,
  },
  {
    name: "Tool Box - Metal",
    description: "Heavy duty metal tool storage box",
    category: "industrial",
    price: 1800,
    costPrice: 1200,
    quantity: 15,
    minStock: 3,
    unit: "piece",
    sku: "IN003",
    images: [],
    isActive: true,
  },

  // Office Stationery
  {
    name: "Ball Pen - Blue (Pack of 10)",
    description: "Smooth writing ball pens",
    category: "office",
    price: 80,
    costPrice: 50,
    quantity: 300,
    minStock: 50,
    unit: "pack",
    sku: "OF001",
    images: [],
    isActive: true,
  },
  {
    name: "A4 Paper Ream - 500 Sheets",
    description: "75 GSM copier paper",
    category: "office",
    price: 350,
    costPrice: 280,
    quantity: 100,
    minStock: 20,
    unit: "ream",
    sku: "OF002",
    images: [],
    isActive: true,
  },
  {
    name: "Stapler with Pins",
    description: "Desktop stapler with 1000 pins",
    category: "office",
    price: 180,
    costPrice: 110,
    quantity: 50,
    minStock: 10,
    unit: "set",
    sku: "OF003",
    images: [],
    isActive: true,
  },
  {
    name: "Sticky Notes - Neon (Pack of 5)",
    description: "Colorful sticky notes 3x3 inch",
    category: "office",
    price: 120,
    costPrice: 70,
    quantity: 80,
    minStock: 20,
    unit: "pack",
    sku: "OF004",
    images: [],
    isActive: true,
  },
]

export const accounts: Omit<Account, "_id" | "createdAt">[] = [
  // Assets
  { code: "1000", name: "Cash", type: "asset", subtype: "current", balance: 500000, isActive: true },
  { code: "1010", name: "Bank Account", type: "asset", subtype: "current", balance: 1500000, isActive: true },
  { code: "1100", name: "Accounts Receivable", type: "asset", subtype: "current", balance: 350000, isActive: true },
  { code: "1200", name: "Inventory", type: "asset", subtype: "current", balance: 800000, isActive: true },
  { code: "1300", name: "Prepaid Expenses", type: "asset", subtype: "current", balance: 50000, isActive: true },
  { code: "1500", name: "Furniture & Fixtures", type: "asset", subtype: "fixed", balance: 200000, isActive: true },
  { code: "1510", name: "Equipment", type: "asset", subtype: "fixed", balance: 150000, isActive: true },
  { code: "1600", name: "Accumulated Depreciation", type: "asset", subtype: "fixed", balance: -50000, isActive: true },

  // Liabilities
  { code: "2000", name: "Accounts Payable", type: "liability", subtype: "current", balance: 280000, isActive: true },
  { code: "2100", name: "Accrued Expenses", type: "liability", subtype: "current", balance: 45000, isActive: true },
  { code: "2200", name: "GST Payable", type: "liability", subtype: "current", balance: 85000, isActive: true },
  { code: "2300", name: "Short-term Loan", type: "liability", subtype: "current", balance: 200000, isActive: true },
  { code: "2500", name: "Long-term Loan", type: "liability", subtype: "non-current", balance: 500000, isActive: true },

  // Equity
  { code: "3000", name: "Owner Capital", type: "equity", subtype: "capital", balance: 1500000, isActive: true },
  { code: "3100", name: "Retained Earnings", type: "equity", subtype: "retained", balance: 390000, isActive: true },
  { code: "3200", name: "Drawings", type: "equity", subtype: "drawings", balance: 0, isActive: true },

  // Revenue
  { code: "4000", name: "Sales Revenue", type: "revenue", subtype: "operating", balance: 0, isActive: true },
  { code: "4100", name: "Service Revenue", type: "revenue", subtype: "operating", balance: 0, isActive: true },
  { code: "4200", name: "Interest Income", type: "revenue", subtype: "other", balance: 0, isActive: true },
  { code: "4300", name: "Other Income", type: "revenue", subtype: "other", balance: 0, isActive: true },

  // Expenses
  { code: "5000", name: "Cost of Goods Sold", type: "expense", subtype: "cost", balance: 0, isActive: true },
  { code: "5100", name: "Salary Expense", type: "expense", subtype: "operating", balance: 0, isActive: true },
  { code: "5200", name: "Rent Expense", type: "expense", subtype: "operating", balance: 0, isActive: true },
  { code: "5300", name: "Utilities Expense", type: "expense", subtype: "operating", balance: 0, isActive: true },
  { code: "5400", name: "Office Supplies Expense", type: "expense", subtype: "operating", balance: 0, isActive: true },
  { code: "5500", name: "Depreciation Expense", type: "expense", subtype: "operating", balance: 0, isActive: true },
  { code: "5600", name: "Insurance Expense", type: "expense", subtype: "operating", balance: 0, isActive: true },
  { code: "5700", name: "Marketing Expense", type: "expense", subtype: "operating", balance: 0, isActive: true },
  { code: "5800", name: "Interest Expense", type: "expense", subtype: "financial", balance: 0, isActive: true },
  { code: "5900", name: "Miscellaneous Expense", type: "expense", subtype: "other", balance: 0, isActive: true },
]

export const customers: Omit<Customer, "_id" | "createdAt">[] = [
  {
    name: "ABC Industries Pvt Ltd",
    email: "purchase@abcindustries.com",
    phone: "9876543210",
    address: {
      street: "123 Industrial Area",
      city: "Ahmedabad",
      state: "Gujarat",
      pincode: "380015",
      country: "India",
    },
    gstNumber: "24ABCDE1234F1Z5",
    creditLimit: 100000,
    balance: 25000,
  },
  {
    name: "XYZ Corporation",
    email: "accounts@xyzcorp.com",
    phone: "9876543211",
    address: { street: "456 Business Park", city: "Rajkot", state: "Gujarat", pincode: "360001", country: "India" },
    gstNumber: "24XYZAB5678G2H6",
    creditLimit: 150000,
    balance: 45000,
  },
  {
    name: "Modern Office Solutions",
    email: "info@modernoffice.com",
    phone: "9876543212",
    address: { street: "789 Commercial Complex", city: "Surat", state: "Gujarat", pincode: "395003", country: "India" },
    gstNumber: "24MODOF9012I3J7",
    creditLimit: 75000,
    balance: 0,
  },
]
